[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "chpl"
authors = [{name = "ACFSJ", email = "annacfelixs@gmail.com"}]
dynamic = ["version", "description"]
